- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

- docker tag udagram-api-feed olowoyinka/udagram-api-feed:v1
- docker tag udagram-api-user olowoyinka/udagram-api-user:v1
- docker tag udagram-frontend olowoyinka/udagram-frontend:v1
- docker tag udagram-reverseproxy olowoyinka/udagram-reverseproxy:v1

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push olowoyinka/udagram-api-feed:v1
- docker push olowoyinka/udagram-api-user:v1
- docker push olowoyinka/udagram-frontend:v1
- docker push olowoyinka/udagram-reverseproxy:v1